### ISSUE TITLE
How to change which drivers are installed?

### ISSUE THREAD

**Issue by SVPA-TrinityFox** [markelog/gulp-wdio#5]
If I wanted to set a configuration option to only install the driver for Chrome, as opposed to Chrome and Firefox, where might I do that?

**Comment by markelog** [comment]
Sorry, missed this issue.

[`selenium-standalone`](https://github.com/vvo/selenium-standalone) includes all drivers already, so not only those two, but also should work in Safari and IE

**Comment by SVPA-TrinityFox** [comment]
You misunderstand- I want ***only*** the driver for Chrome to download/install, with no other browsers.  Is this at all possible?

**Comment by markelog** [comment]
Why?

**Comment by SVPA-TrinityFox** [comment]
The project I'm working on is exclusively targeted for Chrome, so I've no need for the other browsers in my daily usage.
